from .arena import *


class Rules:
    def __init__(self, json):
        self.max_tick_count = json.get("max_tick_count")
        self.arena = Arena(json.get("arena"))
        self.team_size = json.get("team_size")
        self.seed = json.get("seed")
        self.ROBOT_MIN_RADIUS = json.get("ROBOT_MIN_RADIUS")
        self.ROBOT_MAX_RADIUS = json.get("ROBOT_MAX_RADIUS")
        self.ROBOT_MAX_JUMP_SPEED = json.get("ROBOT_MAX_JUMP_SPEED")
        self.ROBOT_ACCELERATION = json.get("ROBOT_ACCELERATION")
        self.ROBOT_NITRO_ACCELERATION = json.get("ROBOT_NITRO_ACCELERATION")
        self.ROBOT_MAX_GROUND_SPEED = json.get("ROBOT_MAX_GROUND_SPEED")
        self.ROBOT_ARENA_E = json.get("ROBOT_ARENA_E")
        self.ROBOT_RADIUS = json.get("ROBOT_RADIUS")
        self.ROBOT_MASS = json.get("ROBOT_MASS")
        self.TICKS_PER_SECOND = json.get("TICKS_PER_SECOND")
        self.MICROTICKS_PER_TICK = json.get("MICROTICKS_PER_TICK")
        self.RESET_TICKS = json.get("RESET_TICKS")
        self.BALL_ARENA_E = json.get("BALL_ARENA_E")
        self.BALL_RADIUS = json.get("BALL_RADIUS")
        self.BALL_MASS = json.get("BALL_MASS")
        self.MIN_HIT_E = json.get("MIN_HIT_E")
        self.MAX_HIT_E = json.get("MAX_HIT_E")
        self.MAX_ENTITY_SPEED = json.get("MAX_ENTITY_SPEED")
        self.MAX_NITRO_AMOUNT = json.get("MAX_NITRO_AMOUNT")
        self.START_NITRO_AMOUNT = json.get("START_NITRO_AMOUNT")
        self.NITRO_POINT_VELOCITY_CHANGE = json.get("NITRO_POINT_VELOCITY_CHANGE")
        self.NITRO_PACK_X = json.get("NITRO_PACK_X")
        self.NITRO_PACK_Y = json.get("NITRO_PACK_Y")
        self.NITRO_PACK_Z = json.get("NITRO_PACK_Z")
        self.NITRO_PACK_RADIUS = json.get("NITRO_PACK_RADIUS")
        self.NITRO_PACK_AMOUNT = json.get("NITRO_PACK_AMOUNT")
        self.NITRO_PACK_RESPAWN_TICKS = json.get("NITRO_PACK_RESPAWN_TICKS")
        self.GRAVITY = json.get("GRAVITY")
